### ISSUE TITLE
dtwclust - examples cannot be reproduced

### ISSUE THREAD

**Issue by golnazshah** [asardaes/dtwclust#14]
Hello, 

I have started using dtwclust package. However, there are several examples that cannot be run. So far I have encountered the following problems:

1. create_dtwclust: the function cannot be found.
2.  page 27:  reinterpolate(CharTraj, new.length = max(lengths(CharTraj))), new.length should newLength and R does not recognize lengths. After making some changes, I get:

 series <- reinterpolate(CharTraj, newLength = max(length(CharTraj)))
**Error in xy.coords(x, y) : 
  'x' is a list, but does not have components 'x' and 'y'**

Thank you, 
Golnaz

**Comment by asardaes** [comment]
Hello, are you sure you are using the newest version of the package? It might be a good idea to update your R and RStudio installation if necessary. The `newLength` parameter was removed quite a while ago. On the other hand, `create_dtwclust` was added more recently, but you shouldn't use that anymore, since now the main function is `tsclust`.

Use `sessionInfo()` to find out your R version, the first line of output will tell you (latest version is 3.4.0).

Use `utils::packageVersion("dtwclust")` to find out the version of the package (latest CRAN version is 3.2.0)
