### ISSUE TITLE
Prototype before clustering?

### ISSUE THREAD

**Issue by MendesRa** [asardaes/dtwclust#19]
Im analyzing time series of dominant frequency for an insect genus. The objectives are to (1) calculate  acoustic distance matrices between pairs of species and populations and (2) use hierarchical cluster analysis to reveal the structure of the acoustic signals amongst the genus. I have a huge data set with several time-series per individual and several individuals per species. I was thinking that the best way to do this is to calculate the time-series prototype for each individual, using the DBA function and then used this series as input to calculate the distance matrices and the cluster analysis. Is it correct to use prototypes this way?

**Comment by asardaes** [comment]
Probably not. Regardless of what prototype you use, it doesn't make sense to calculate a prototype for a single (possibly multivariate?) time series, you always need a group of series as input for the prototyping function.

Usually one uses clustering approaches to create the groups and then calculates the prototype of the resulting clusters afterwards, i.e. the prototypes are an output of the clustering procedure.

Moreover, you mentioned "acoustic distance measure". Does this mean you're using a custom distance function? Because it's hard to say if DBA would work nicely with non-DTW distances.

**Comment by asardaes** [comment]
After reading your question again, I suppose you mean the prototype for all the series belonging to the same individual. In that case, then yes, that sounds logical. Whether that's correct depends on your own definitions.

**Comment by MendesRa** [comment]
Yes, that is what I meant. It makes sense (biologically) to me, I just
wasn´t sure if it was mathematically correct.
Im thinking in using DTW-distance, I call it acoustic distance, because in
the end it will give the acoustic similarity between species.

Thank you for your help!

Raquel Mendes

2017-09-12 17:35 GMT+01:00 Alexis Sardá <notifications@github.com>:
