### ISSUE TITLE
A question about the Hierarchical Clustering in dtwclust()

### ISSUE THREAD

**Issue by sergiowang** [asardaes/dtwclust#4]
When using the Hierarchical Clustering in dtwclust() like `result<-dtwclust(data,'hierarchical',distance = 'dtw')`, does the `result@k` always return '2' and the `result@cluster` return the time series in two clusers even though the number of bottom branches are more than two ?
Or dose it mean the given time series data set is best divided when clustered into two clusters ?

**Comment by asardaes** [comment]
The hierarchy created by the clustering algorithm does *not* imply a specific number of clusters by itself. You can either specify the number of desired clusters when calling `dtwclust` (the default value of `k` is 2, that's why you are always getting that number of clusters), or you can use the `cutree` function on `result`. Another option is to look at the dendrogram and visually assess where the best partition would be created, and extract the amount of clusters that would result (look at the examples included in the `identify.hclust` function, and the documentation for `hclust`).
