### ISSUE TITLE
Definition of multivariate time series

### ISSUE THREAD

**Issue by vidarsumo** [asardaes/dtwclust#54]
I was just reading [Vignette with theory](https://cran.r-project.org/web/packages/dtwclust/vignettes/dtwclust.pdf) and I'm a bit confused when you talk about multivariate time series. 

Do you differentiate between many time series and multivariate time series? 

I have a data set of 6,000 time series (sales data from one client) and I want to create clusters.  These can be very different products like cosmetics, beverages and candy. I simply look at this as many time series, some are related, like a subgroup of the beverages, but many are not, like lipstick and a soda. The products are of very different length, many only with 1 or 2 observation (1-2 months of monthly sales data) while other have many months of data.

I'm not sure if I need to do anything special after reading this vignette because I got a bit confused when you mentioned multivariate time series.

**Comment by asardaes** [comment]
Have you checked the sample data included in `CharTrajMV`? I'd say that considering series as multivariate can be subject to interpretation. In said data, every multivariate series contains 3 univariate series that were recorded for the same individual doing the same character, so there are many series, but some of them can be considered together as one because they came from the same "entity".

**Comment by vidarsumo** [comment]
Ok that's what I thought but wasn't sure. I was a bit confused since in a field like economics you talk about multivariate model like VAR but there you might have few time series from different "entity", i.e. wage, inflation, exchange rate, unemployment etc.
